baseurl: /baltimore
permalink: pretty
markdown: kramdown
paginate: 5
repo: Baltimore
github_org: maptime
maptime:
  chapter: Maptime Baltimore
  twitter: MaptimoreBmore
  #disqus: YOUR DISQUS USERNAME
